plugins:
  - jekyll-feed
  - jekyll-sitemap

# SEO Stuff
author: srnovus
description: Documentacion oficial de Fedired Social.
lang: es
locale: es_GT
url: "https://docs.fedired.com"
baseurl: ""
permalink: :title

# RSS feeds
feed:
  posts_limit: 20

# Netlify redirects
include:
  - _redirects
